### ISSUE TITLE
Plenty of errors after starting the main programe

### ISSUE THREAD

**Issue by Synthyan** [jwaxy/aternosboom#1]
You should see for yourself,

misspelled program*

**Comment by jwaxy** [comment]
Can you send the errors? So I can help you.

**Comment by jwaxy** [comment]
It works for me. Did you install the requirements?

**Comment by Synthyan** [comment]
Here, and yes I did install the requirements - also might want to fix the 1st instead of 1st
![Debug](https://user-images.githubusercontent.com/69605857/211359282-e05943fc-f421-4277-86ef-a3b5319e5260.png)

**Comment by Synthyan** [comment]
at this point i don't know if its a programme issue or a python issue

**Comment by jwaxy** [comment]
Hello @Synthyan ! Sorry for late reply. I didn't see the message. I added a new commit that adds verbose mode to the login function because it looks like that the error is coming from that function. Can you download & git clone the latest version and try passing the -v argument to the script then send me the output ?

**Comment by Synthyan** [comment]
![Debug2](https://user-images.githubusercontent.com/69605857/217338758-7f050dc3-aaf3-4bc3-b05a-3e488c28c9d7.png)
![Debug2i](https://user-images.githubusercontent.com/69605857/217340337-0d04f3b6-62eb-4f84-a39c-1032bf1a8db2.png)
Here

**Comment by jwaxy** [comment]
i think your target logged in using a google account this tool is only for accounts created with mail and password. Sorry!

**Comment by Synthyan** [comment]
ah, ok thank you

**Comment by jwaxy** [comment]
I am marking this as solved, okay?
